fix: integrate graph building with the whole extension (#34)
* feat: get a sampleinput.ts as input

get input from sampleinput.ts constructed based on types.ts

* feat: visualization of graph

upload webview dir for visualization

* fix: tsconfig

added missing semicolon

* style: reformat graph.ts

* refactor: remove all extension orchestration logic in graph.ts

* fix: add `showGraphView` to display call graph

* feat: add test command for visualizing graph

* fix: compilation error

```
ERROR in thought-flow/extension/tsconfig.json
thought-flow/extension/tsconfig.json
[tsl] ERROR
      TS5103: Invalid value for '--ignoreDeprecations'.
ts-loader-default_e3b0c44298fc1c14

ERROR in thought-flow/extension/src/analyzer.ts
4:14-22
[tsl] ERROR in /thought-flow/extension/src/analyzer.ts(4,15)
      TS2305: Module '"@/types"' has no exported member 'TestType'.
ts-loader-default_e3b0c44298fc1c14
```

* feat: add `encodeGraphIds()`

* fix: encode graph data before inserting into html for safety and compatibility

* refactor: use `postMessage` for safer graph data loading

Updates `graphScript.js` to listen for `INIT_GRAPH` messages and initialize Cytoscape accordingly

* feat: improve graph debug output in `showGraphView()`

* test: slashes in node id

* docs: update README with more efficient dev workflow

* fix: move graph webview templates to `src/templates`

* fix: update path to templates

---------

Co-authored-by: xmonokumax <1155194590@link.cuhk.edu.hk>